### ISSUE TITLE
database.TestCalculateAverage is flaky

### ISSUE THREAD

**Issue by aDotInTheVoid** [gpuctl/gpuctl#113]
It's failed CI here: https://github.com/gpuctl/gpuctl/actions/runs/7856261718/job/21438860855.

And can be reproduced locally:

```
alona@Ashtabula:~/dev/gpuctl$ go test -short ./internal/database/ -count 10
--- FAIL: TestCalculateAverage (0.00s)
    prune_test.go:78: calculateAverage() = {gpu-1 55 30 4500 55 72.5 67.5 1.15 110 1525 1825 725 925 1625140800 [{2 Process2 300} {1 Process1 250}]}, want {gpu-1 55 30 4500 55 72.5 67.5 1.15 110 1525 1825 725 925 1625140800 [{1 Process1 250} {2 Process2 300}]}
FAIL
FAIL    github.com/gpuctl/gpuctl/internal/database      0.017s
FAIL
```

Note: You may need to repeat this command a few times to get it to work, as it's non-deterministic. The `-count` flag is needed to run multiple times, and bypass Go's builtin cacheing

---

I've not investigated the reason, but it smells like rellying on map iteration order.

CC @Euphoride

**Comment by Euphoride** [comment]
I'll look into this soon, but as far as I know, map iteration order is not deterministic but iteration order is not corrupted if the map is altered during iteration in Go. If this invariant is not true, then that will explain the sporadic failure.

**Comment by aDotInTheVoid** [comment]
>  The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next. If a map entry that has not yet been reached is removed during iteration, the corresponding iteration value will not be produced. If a map entry is created during iteration, that entry may be produced during the iteration or may be skipped. The choice may vary for each entry created and from one iteration to the next. If the map is nil, the number of iterations is 0. 

From <https://go.dev/ref/spec#RangeClause>

So it looks like

1. Iterating over the same map may yield a different order
2. Adding items while iterating may or may not yield them, but won't cause memory corrpution.
