### ISSUE TITLE
determine isFree using python process information/ store this in db

### ISSUE THREAD

**Issue by aDotInTheVoid** [gpuctl/gpuctl#125]

**Comment by danielg0** [comment]
I would be interested in hearing some opinions on how/where exactly we want to calculate/store this `isFree` value. The way I see it, we have three options:

- Similarly to every value we're currently tracking, we pass the full process list through the groundstation and database and webapi as is, and then have the frontend determine whether to mark a machine as "in use"
  - This solution is probably the most flexible if we ever want to start doing long term tracking of processes or computation more complex than "is there a process in this list, if so, it's being used"
  - Requires a fair bit of info to be sent with each frontend packet, and more work on the frontend side
- Store the full process list for each stat sample in the database, and calculate "is free" on a call to `LatestStats()`
  - Simple frontend implementation (just display a name and green/red emoji depending on value of boolean)
- Calculate whether a gpu is free at the point when the data goes into the database (storing it in the database as a boolean value, with a string for the user running it) (edit: this can also, and makes more sense to be done in the satellite)
  - Simple for database schema to implement
  - `IsFree` is only ever calculated for a particular stat once
  - Not especially flexible if we want to track processes' over time

I'm going to start making changes under the assumption we go for one of the last two, and I lean toward the last one, largely for it's simplicity, but I'd be interested in hearing other people's opinion

**Comment by Euphoride** [comment]
@danielg0 At the moment, the only sensible decision is the third one. Here's why:

**Proposal One**
The process list must go through the groundstation. It thus won't ever touch the database layer unless it is stored in the database, but it's worth noting that the only way the webapi and groundstation have coupling is via the database layer (which should be statelessly interacting with the database). This solution is the same as the second one then, or doesn't make sense semantically.

**Proposal Two**
The process list should be noted in the database. The only way to do this effectively is to use a diff-based storage mechanism with fast-lookup using things like TimescaleDB. Dumping the full process list, even with indexed columns, with time series data becomes incredibly inefficient. That said, **do not** need to do the work on the database side and should instead develop a custom SQL function that calculates is_free and places it as a column on the LatestData table to hide away the non-trivial complications of this approach. We should, as said, only do this approach if we intend to do long-term tracking of processes. We do not, and we are nearing our final sprint, to which we do not expect to do this. It's a slow-down.

**Proposal Three**
This is the most sensible solution. Satellites should simply send a boolean flag in their updates, the groundstation should store this with each sample, and the WebAPI needs not do any new work.

**Comment by NathanielB123** [comment]
Yeah I agree, third proposal (with the modification that it should be done in the satellite, so full process info never needs to be sent anywhere) sounds by far the most reasonable to me.

**Comment by danielg0** [comment]
Cool, will start making some progress on this. Thanks for your input

**Comment by danielg0** [comment]
Discussed API with @YRMYJASKA. He's modified the returned GPU stat to add:

```go
type GPUStatSample struct {
    ...,
    RunningProcesses []GPUProcInfo `json:"processes"`
}

type GPUProcInfo struct {
	Pid     uint64  `json:"pid"`
	Name    string  `json:"name"`
	MemUsed float64 `json:"used_memory"`
	Owner   string  `json:"owner"`
}
```

He's going to modify the satellite so the returned list contains only processes that are on our whitelist of "in-use" names (ie. that're python). Then the groundstation will check if the list is empty or not

**Comment by danielg0** [comment]
I'm planning on modifying the database schema to add:

```
    InUse boolean NOT NULL,
    UserName text NOT NULL DEFAULT '',
```

Edit: looks like `User` is a SQL reserved name, like `Group`, so I'm going to call the row `UserName`

**Comment by danielg0** [comment]
After discussion with Nathaniel, the frontend will expecting a JSON reply of the form:

`{..., in_use: bool, user: string}`
