### ISSUE TITLE
Functionality for rebooting machines remotely

### ISSUE THREAD

**Issue by aDotInTheVoid** [gpuctl/gpuctl#130]
Needs to be secure, we can't just allow anyone to reboot a machine remotely

**Comment by NathanielB123** [comment]
I think this was mentioned somewhere else, but to reinforce: we DON'T need to reboot machines in a completely automated way (which would require being able to SSH into the machines with an account with permissions to reboot them). Giving Ben a command he can copy, alt-tab to his terminal with and run manually is fine.

**Comment by Euphoride** [comment]
@NathanielB123, that said, we do in fact do it remotely :) #108 needs to be unfudged but it's there.

**Comment by danielg0** [comment]
> we do in fact do it remotely

How are we rebooting without root access?

**Comment by NathanielB123** [comment]
woah what? how does it work?

**Comment by Euphoride** [comment]
Let me clarify: we need an SSH key that allows for root access, but the functionality is there to automatically reboot a machine when we detect the daemon is not running anymore, however it is reachable via ICMP.

**Comment by aDotInTheVoid** [comment]
Wait, if it's reachable by ICMP, but the satelite is down, why are we rebooting? Surely we just restart the satellite.

**Comment by Euphoride** [comment]
I think I've misunderstood *reboot* here, and I've been referring to restarting the daemon. That said, this should be a case of using that infra to complete this.

**Comment by aDotInTheVoid** [comment]
No, Ben's said rebooting (as in powering off and on the whole OS) is a maintenence task he sometimes does.

For auto-restarting just the satellite daemon, see #73. That's alot easier, as it's not privaleged.

**Comment by Euphoride** [comment]
#188

**Comment by Euphoride** [comment]
Done
