### ISSUE TITLE
Support Permanent Logging-out

### ISSUE THREAD

**Issue by NathanielB123** [gpuctl/gpuctl#145]
The front-end is not allowed to modify it's own cookies, so we need a back-end endpoint for revoking auth keys.

**Comment by NathanielB123** [comment]
@YRMYJASKA hope you don't mind me assigning you to this - Daniel was saying you don't have many tickets, and this is a mostly back-end issue I think

**Comment by YRMYJASKA** [comment]
yeah no problem, I was looking for things to do in any case
