### ISSUE TITLE
Implement machine info changes and machine deletion for the inmemory database

### ISSUE THREAD

**Issue by danielg0** [gpuctl/gpuctl#154]
When you do this, alter the tests to remove the workaround introduced in f419c2ddb9a46543993b6d5bab9ae12cb2f1dc19 (there's another case of it in the test that follows to)

**Comment by Euphoride** [comment]
#156

**Comment by Euphoride** [comment]
Blocked on #143

**Comment by Euphoride** [comment]
Done
