### ISSUE TITLE
Retrieve all machine stats from API and display on frontend

### ISSUE THREAD

**Issue by aDotInTheVoid** [gpuctl/gpuctl#16]
Technical Spec:
- [x] `api/stats/all`
- [x] Decide on some standard JSON format
- [x] Refresh stats after period of time
- [x] Go API Server (The Go Programming Language/linked tutorials on Discord)
- [x] TSX webpage shit that displays the data
- [x] React shit that fetches the data from the backend
- [x] Tests

**Comment by NathanielB123** [comment]
Feature complete now, just needs tests

**Comment by NathanielB123** [comment]
https://github.com/gpuctl/gpuctl/pull/10
