### ISSUE TITLE
Graphs on frontend

### ISSUE THREAD

**Issue by danielg0** [gpuctl/gpuctl#212]
The focused card view has some graphs showing long term data

**Comment by NathanielB123** [comment]
Alona mentioned https://d3-graph-gallery.com/index.html, which looks pretty cool - time for more dependencies!

**Comment by YRMYJASKA** [comment]
I got assigned to this, but is there a spec already of what is needed on the back-end? @NathanielB123 @danielg0

**Comment by NathanielB123** [comment]
https://github.com/gpuctl/gpuctl/pull/221

**Comment by YRMYJASKA** [comment]
Functionality should be merged in
