### ISSUE TITLE
Seperate status codes for remove machine failure

### ISSUE THREAD

**Issue by sirjacobofglais** [gpuctl/gpuctl#227]

**Comment by sirjacobofglais** [comment]
We want a different status code for when a) there is a network/database error, and b) when ssh to the satellite fails. This is so we can show different error messages on the frontend.

**Comment by YRMYJASKA** [comment]
Okay, should be simple to add. Which status code do you want for each?

**Comment by sirjacobofglais** [comment]
Nothing immediately comes to mind - find something you like

**Comment by YRMYJASKA** [comment]
HTTP status codes have specific meanings to them and I don't think its a particularly good idea to bastardize some to report specific errors. Would you be open to handling the body of the response? i.e. the API would respond with `500` status but the response body contains `Database error:....` or (_not xor_) `Deboarding error:...`. This is what is happening already, excep that the errors were not being wrapped with `Database/Deboarding error`.

**Comment by NathanielB123** [comment]
Daniel says "503 - Service Unavailable" *might* be applicable? Or we could use some random status code >511 (because those are unused) maybe?

Parsing the response body wouldn't be the end of the world, but it's a bit ugly

**Comment by NathanielB123** [comment]
Parsing the response body wouldn't be the end of the world, but it's a bit ugly

**Comment by NathanielB123** [comment]
Actually, what if we returned errors in a JSON format? i.e. `{"Deboarding": "..."}`/`{"Database": "..."}` - probably a more ambitious change, but would make parsing easy @YRMYJASKA 

Daniel says `slog` can print out JSON, so that might be helpful?

**Comment by YRMYJASKA** [comment]
Returning JSON is a-okay, just have to do a little bit of fanangling, but should be a ~ 5 line change. I will do it asap

**Comment by YRMYJASKA** [comment]
ugh, common femto L. It is not intended for us to return stuff from POST requests... Going with status code approach as I cba

**Comment by YRMYJASKA** [comment]
I will do it so that `512` means `only onboarding had an error`, `513` means `only db had an error`, and `514` means `both onboarding and db had errors`
