### ISSUE TITLE
satelite: load gsAddr from CLI flags or config file

### ISSUE THREAD

**Issue by aDotInTheVoid** [gpuctl/gpuctl#34]
I'd suggest that this reads from a configuration file for now, until we have DNS-based service discovery that's automated. ~~Maybe we need to build in a way to parameterise our satellites through a TOML file?~~ See #28.

_Originally posted by @Euphoride in https://github.com/gpuctl/gpuctl/pull/27#discussion_r1460162260_

**Comment by Euphoride** [comment]
Done, loads from config file in #68

**Comment by aDotInTheVoid** [comment]
let’s leave this open until that lands
