### ISSUE TITLE
figure out configuration

### ISSUE THREAD

**Issue by aDotInTheVoid** [gpuctl/gpuctl#57]
> I'm fine with this PR, but I think we need to decide on a configuration format and stick to it. We now have:
> - An unused toml implementation in `cmd/groundstation/config`
> - Postgres unit tests that only use environment variables and fallback to a hardcoded value
> - control.go that uses go flags and an environment variable that fallsback to the postgres default server

_Originally posted by @danielg0 in https://github.com/gpuctl/gpuctl/pull/55#pullrequestreview-1845028984_

**Comment by Euphoride** [comment]
As of now, server and client use toml configuration. Soon enough we should convert postgres and then we'll be good.

**Comment by aDotInTheVoid** [comment]
Done in #68
