### ISSUE TITLE
Admin Frontend

### ISSUE THREAD

**Issue by aDotInTheVoid** [gpuctl/gpuctl#70]
- [x] Custom Notes for each workstation
- [x] Specific workstation page (probably not necessary, but seems like a good time to start work on it, given we will be adding a bunch more data that couldn't be nicely displayed in table)
- [x] UI for command suggestions (easy to copy to terminal and run)
- [x] Add machines to frontend by hostname

**Comment by NathanielB123** [comment]
Partially implemented by https://github.com/gpuctl/gpuctl/pull/97

**Comment by NathanielB123** [comment]
Workstation page added in https://github.com/gpuctl/gpuctl/pull/221
