### ISSUE TITLE
Auto-restart satlites that haven't contacted up

### ISSUE THREAD

**Issue by aDotInTheVoid** [gpuctl/gpuctl#73]
Either use user-systemd, or:

- See we've not seen a hearbeat
- But we can manage to ping the machine
- So SSH in, and start the satelite again

**Comment by aDotInTheVoid** [comment]
Done in #108, but the git's fudged, so it's currently impossible to review.

**Comment by Euphoride** [comment]
Done in #150, clean PR, waiting on review

**Comment by Euphoride** [comment]
#150 merged
