### ISSUE TITLE
Prune database stats

### ISSUE THREAD

**Issue by danielg0** [gpuctl/gpuctl#89]
Currently, once a stat is recorded, it stays in the database forever. This isn't sustainable (or needed) longterm. Instead we should periodically go through the database and drop stats from some time ago. Potentially, we may want to instead keep some or aggregate the dropped ones so we can still do long term graphs (ie. keep one stat for each hour so we can do a graph of usage over the week).

Ideally this is all configurable.

Essentially, it does something like this (https://borgbackup.readthedocs.io/en/stable/usage/prune.html) every so often, automatically

**Comment by Euphoride** [comment]
Done in #107
